
<section class="p-page-container">

	<div class="nav-brand">
		<a href="<?=config::get('url');?>" style="text-decoration: none;">
			<img src="//back-end.ninja/assets/images/new_ninja.png"></img>
		</a>
	</div>

	<div class="row m-n ">

		<div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4 col-xl-2 col-xl-offset-5 m-t-lg">

			<section class="panel">
				<header class="panel-heading text-center">
					
					Sign up

				</header>
				

				<form action="<?=config::get('url');?>" class="panel-body" method="get">

					<b style="font-weight:700;">
						Thank you.
					</b>

					<br />
					<br />

					<button type="submit" class="btn btn-success btn-block" style="opacity:0.9">Continue</button>

				</form>

			</section>

		</div>

	</div>

</section>
