
<div id="Project_Stats">

  <style>

    #Project_Stats form.settings {
      border: 1px solid grey;
      border-radius: 2px;
      padding: 12px 18px;
    }

    #Project_Stats label {
      margin: 4px 0;
    }

    #Project_Stats input[type="submit"] {
      margin: 12px 0;
    }

  </style>

  <h1>Project_Stats</h1>

  <form class="settings" method="POST">
    
    <label>
      <p>Project path</p>
      <input
        type="text"
        name="settings[project_path]"
        value="{$this->settings['project_path']}"
      />
    </label>

    <label>
      <p>Exclude paths</p>

      <ul style="list-style: none;padding-left: 0;">
        <?=$this->render_exclude_paths_options_html();?>
      </ul>
    </label>


    <input type="submit" value="Draw stats" />

  </form>

  <div class="results">
    
    <?=$this->render_results_html();?>

  </div>

</body>
