#!/bin/bash

bold=$(tput bold)
normal=$(tput sgr0)

test_script_file_names=(

	"lint_js"

	"lint_php"

	# "lint_php_tests"

	# "test_php_syntax"
)

verbose=false

if ( [ "$1" == '-v' ] || [ "$1" == '--verbose' ] )
then
	verbose=true

	clear
fi


if [[ "$verbose" = true ]]
then
	printf "\nRunning tests: \n\n"

	c=0
	for test_file_name in "${test_script_file_names[@]}"
	do
		((c=c+1)); printf "  ${c}. ${test_file_name} \n"
	done

	printf "\n"
fi


c=0
for test_file_name in "${test_script_file_names[@]}"
do
	((c=c+1))

	if [[ "$verbose" = true ]]
	then
		printf "\n\n${bold}${c}. ${test_file_name}${normal}\n\n"

		bash "sh/${test_file_name}" -v || exit 1

		printf "\n\n"
	else
		bash "sh/${test_file_name}" || exit 1
	fi
done

if [[ "$verbose" = true ]]
then
	printf "\n\n\e[32mAll tests completed. No errors found. ${normal}\n\n\n"
fi
