#!/bin/bash

bold=$(tput bold)
normal=$(tput sgr0)


SRC=("src")


verbose=true

if ( [ "$1" == '-v' ] || [ "$1" == '--verbose' ] )
then
	verbose=true

	printf " for  \$filepath  in  '${SRC}'  \n\n"
	printf " -name '*.php'  \n\n"
	printf " -or -name '*.phtml'  \n\n"
	printf " -not -path '*/plugins/*'  \n\n"
	printf "     php  -d display_errors  -l  -f '\$filepath'  \n\n"
fi


for filepath in $( find "${SRC}" \( -name '*.php' -or -name '*.phtml' \) -not -path '*/plugins/*' )
do

	result=$(  php  -l  -d display_errors  -f "$filepath"  )


	if [[ $result == *"No syntax errors"* ]]
	then

		if [[ "$verbose" = true ]]
		then
	    	printf "\n\e[32m OK  ${normal} $filepath"
	    else
	    	printf "."
	    fi

    else

		printf "\n\e[31m ERR ${normal} $filepath"

		printf "\n\n\n\e[31m\e[3m${result}"

		printf "\n\n\n\n${normal}"

		exit 1
	fi
done


if [ "$verbose" = true ]
then
	printf "\n\n"
else
	printf "\n"
fi


printf "Done. No errors found."

