
<section class="p-page-container">

	<div
	 class="nav-brand"
	 style="
	 	display: block;
		width: 100%;
		text-align: center;
		font-size: 50px;
		color: rgba(79, 123, 40, 1.0);
		opacity: .6;
		margin-bottom: 30px;
		text-decoration:none;
	 "
	>
		<a href="<?=config::get('url');?>" style="text-decoration: none;">
			<img src="//back-end.ninja/assets/images/new_ninja.png"></img>
		</a>
	</div>

	<div class="row m-n ">

		<div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4 col-xl-2 col-xl-offset-5 m-t-lg loginBox">

			<section
			 class="panel"
			 style="
			 	opacity: 0.95;
			 	background-color: rgba(255, 255, 255, 0.7);
			 "
			>

				<header class="panel-heading text-center">
					
					Reset your password

				</header>

			    <form method="post" class="panel-body">

					<?php if(isset($params['msg'])): ?>
						<div class="loginError">
							<b style="font-weight:700;">
								<?=$params['msg'];?>
							</b>
						</div>

					<?php endif; ?>
					
			     	<div class="form-group" style="width:100%;">
						
						<input type="text" placeholder="Username or Email" class="form-control" name="username" value="">
			      	</div>
			      	
			      	<button type="submit" class="btn btn-success btn-block" style="opacity:0.9">Continue</button>
			      
			    </form>
	  
	    	</section>
	    </div>
	</div>
</section>
