
<!-- Nothing to see here. Just a dirty old project copy -->

<div id="page-content">
    <!-- Blank Header -->
    <div class="content-header">
    	<br class="topMargin">
        <div class="header-section">
            <h1>
                <i class="fa fa-cloud"></i>Webspaces<br><small style="font-size:16px;">Use webspaces as workspaces for your projects. Settings will change according to the active webspace.</small>
            </h1>
        </div>
    </div>
    <ul class="breadcrumb breadcrumb-top">
        <li class="active">Webspaces</li>
    </ul>
    

    <div class="row">
	<div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-lg-8 col-sm-12 col-sm-offset-0">


		
		
		<div class="row">
			<div class="col-xs-12 col-sm-6">
				<a href="/webspace/1" class="block" style="width:100%;" onmouseover="$(this).find('I').css('color','rgb(196, 201, 211)');" onmouseout="$(this).find('I').css('color','rgb(224, 231, 241)');">
				    		
				    <span class="fa-stack fa-lg pull-right" style="width: 88%;padding-right: 0px; display: inline; position: absolute; color: rgb(224, 231, 241); text-align: right; font-size: 40px; padding-top: 10px;">
				      <i class="fa fa-cloud fa-stack-2x" style="font-size: 40px; width: 100%; text-align: right; padding-right: 8px; color: rgb(224, 231, 241);"></i>
				    </span>
				    
				    <span style="width:88%;">
					    <h4 class="block-header" style="z-index:999">Personal Webspace</h4>
					    <h5 style="z-index:999">webspace.systems <small></small></h5>
					    <h6 style="z-index:999"></h6>
				    </span>
				</a>
		    </div>
			<div class="col-xs-12 col-sm-6">
				<a href="/webspace/2" class="block" style="width:100%;" onmouseover="$(this).find('I').css('color','rgb(196, 201, 211)');" onmouseout="$(this).find('I').css('color','rgb(224, 231, 241)');">
				    		
				    <span class="fa-stack fa-lg pull-right" style="width: 88%;padding-right: 0px; display: inline; position: absolute; color: rgb(224, 231, 241); text-align: right; font-size: 40px; padding-top: 10px;">
				      <i class="fa fa-cloud fa-stack-2x" style="font-size: 40px; width: 100%; text-align: right; padding-right: 8px; color: rgb(224, 231, 241);"></i>
				    </span>
				    
				    <span style="width:88%;">
					    <h4 class="block-header" style="z-index:999">Personal Webspace</h4>
					    <h5 style="z-index:999">webspace.systems <small></small></h5>
					    <h6 style="z-index:999"></h6>
				    </span>
				</a>
		    </div><br style="clear:both;" class="hidden-xs">
			<div class="col-xs-12 col-sm-6">
				<a href="/webspace/new" class="block" style="width:100%;" onmouseover="$(this).find('I').css('color','rgb(196, 201, 211)');" onmouseout="$(this).find('I').css('color','rgb(224, 231, 241)');">
				    		
				    <span class="fa-stack fa-lg pull-right" style="width: 88%;padding-right: 0px; display: inline; position: absolute; color: rgb(224, 231, 241); text-align: right; font-size: 40px; padding-top: 10px;">
				      <i class="fa fa-plus fa-stack-2x" style="font-size: 40px; width: 100%; text-align: right; padding-right: 8px; color: rgb(224, 231, 241);"></i>
				    </span>
				    
				    <span style="width:88%;">
					    <h4 class="block-header" style="z-index:999">New webspace</h4>
					    <h5 style="z-index:999"></h5>
					    <h6 style="z-index:999">Setup a new webspace</h6>
				    </span>
				</a>
		    </div></div>
				
	    </div>
	</div>
    </div>