
<section class="p-page-container">

	<div class="nav-brand">
		<a href="<?=config::get('url');?>" style="text-decoration: none;">
			<img src="//back-end.ninja/assets/images/new_ninja.png"></img>
		</a>
	</div>

	<div class="row m-n ">

		<div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4 col-xl-2 col-xl-offset-5 m-t-lg">

			<section class="panel">

				<header class="panel-heading text-center">
					
					Sign up

				</header>
				

				<form class="panel-body" method="post">

					<?php if(isset($params['msg'])): ?>
						<div class="loginError">
							<b style="font-weight:700;">
								<?=$params['msg'];?>
							</b>
						</div>

					<?php endif; ?>

					
					<div class="form-group">
					<input type="text" placeholder="First and last name" name="name" class="form-control" value="<?=$params['name']??'';?>" />
					</div>
					<div class="form-group">
					<input type="text" name="company" placeholder="Company name (optional)" class="form-control" value="<?=$params['company']??'';?>" />
					</div>
					<div class="form-group">
					<input type="text" name="username" placeholder="Username" class="form-control" value="<?=$params['username']??'';?>" />
					</div>
					<div class="form-group">
					<input type="email" name="email" placeholder="E-mail adress" class="form-control" value="<?=$params['email']??'';?>" />
					</div>
					<div class="form-group">
					<input type="password" name="password" id="inputPassword" placeholder="Password (8+ characters)" class="form-control" value="<?=$params['password']??'';?>">
					</div>

					<?php /*
					<div class="form-group subChoose">
			
						<input type="radio" id="sub_student" name="subscription" value="1" style="height:5px;margin-right:4px;display:none;" />
						<label for="sub_student">Simple Subscription <span style="float:right;">$ 9 / month</span></label>
						<br />
						<input type="radio" id="sub_developer" name="subscription" value="2" style="height:5px;margin-right:4px;display:none;" />
						<label for="sub_developer">Extensive Subscription <span style="float:right;">$ 19 / month</span></label>
						<br />
						<input type="radio" id="sub_enterprise" name="subscription" value="3" style="height:5px;margin-right:4px;display:none;" />
						<label for="sub_enterprise">Enterprise Subscription <span style="float:right;">$ 29 / month</span></label>

					</div>
					*/ ?>


					<button type="submit" class="btn btn-success btn-block" style="opacity:0.9">Continue</button>

				</form>

			</section>

		</div>

	</div>

</section>
